### PR TITLE
Update installation instructions

### PR DESCRIPTION
**Pull request by macdonst**
Signed-off-by: macdonst <simon.macdonald@gmail.com>

### CODE REVIEW

**Review by colepeters — COMMENTED** [review]
Just wondering about the gitignore — it's got a bunch of things like Yarn, NextJS, Nuxt, Gatsy, etc. in there 🤔

**Comment by macdonst** [comment]
@colepeters I just use the global .gitignore from `npx gitignore node`. I can pare it down. The tests aren't passing anyway.

**Review by colepeters — APPROVED** [review]
Awesome, thank you! Realized that's my bad about the failing tests, so thanks for patching that as well!

**Comment by macdonst** [comment]
Setting it up so we can add the focal point to it next.

**Pull request merged**
