### PR TITLE
Focalpoint

### PR DESCRIPTION
**Pull request by macdonst**
Signed-off-by: macdonst <simon.macdonald@gmail.com>

### CODE REVIEW

**Comment by kristoferjoseph** [comment]
👏

**Review by colepeters — COMMENTED** [review]
Nice one! Could we get a couple updates in the readme?

1. Addition of height and focal point in the `variant<N>` description
2. A new example showing the use of height and focal point?

**Comment by macdonst** [comment]
@colepeters added more verbiage into the README.

**Review by colepeters — APPROVED** [review]
Beautiful!

**Pull request merged**
